---
title: "mri_dat_analysis_five"
author: "Philip Anderson; panders2@tamu.edu"
date: "7/20/2018"
output: pdf_document
---

```{r setup, include=FALSE}
library("astsa")
library("tidyverse")
library("tseries")
library("fGarch")
```

# Data Prep + EDA

```{r}
#read in the data
mri <- read.csv("/Users/panders2/Documents/schools/tamu/stat_626/project/stat_626_proj/mri_dat_one.csv")
names(mri) <- c("hour", "minute", "freq", "int_pressure", "atm_pressure", "tot_pressure", "tesla")
str(mri)
```

```{r}
astsa::tsplot(mri$freq, main="Time-Index Plot of Data")
```



```{r}
mri$freq[944] <- ((mri$freq[943] + mri$freq[946]) / 2)
mri$freq[945] <- ((mri$freq[943] + mri$freq[946]) / 2)
astsa::tsplot(mri$freq[920:970], main="Frequency Time Index Plot 920:970 - modified data")
astsa::tsplot(mri$freq, main="Time Index Plot - modified data")
```

```{r}
mri_diff <- diff(mri$freq)
astsa::tsplot(mri_diff)
```

## Formal Tests for Stationarity

Run the differenced series through the battery of unit root tests we learned about.

```{r}
# Dickey-Fuller Test
tseries::adf.test(mri_diff, k=0)
```

```{r}
# Augmented Dickey-Fuller Test
tseries::adf.test(mri_diff)
```

```{r}
# phillips-peron test
tseries::pp.test(mri_diff)
```

## ARIMA Fit
Running the model we came up with previously.

```{r, message=F, results='hide'}
top_mod <- sarima(mri_diff, 3,0,2)
```

```{r, message=F, results='hide'}
acf2(top_mod$fit$residuals)
```

```{r, message=F, results='hide'}
acf2((top_mod$fit$residuals)^2, 100)
```

It honestly doesn't look like there is much to worry about here.  Regardless, let's fit an ARCH.

```{r, message=F, results='hide'}
garch_mod <- tseries::garch(mri_diff, trace=F)
summary(garch_mod)
acf2(garch_mod$residuals^2, 100)
```

```{r}
summary(garch_mod2 <- fGarch::garchFit(~arma(1,0)+garch(1,0), mri_diff))
```

```{r, message=F, results='hide'}
acf2((garch_mod2@residuals))
acf2((garch_mod2@residuals)^2)
```


```{r}
summary(garch_mod3 <- fGarch::garchFit(~garch(1,1), mri_diff))
```

